const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const LicensePlugin = require("webpack-license-plugin");
const { BannerPlugin } = require("webpack");
const TerserPlugin = require("terser-webpack-plugin");
const WebpackShellPluginNext = require("webpack-shell-plugin-next");

module.exports = {
  entry: {
    demo: "./src/demo/demo.ts",
    lib: "./src/exports.ts",
  },
  devtool: "source-map",
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [
          {
            loader: "babel-loader",
            options: require("./babel.config.js"),
          },
        ],
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    modules: ["./", "node_modules"],
    extensions: [".ts", ".js"],
  },
  optimization: {
    minimizer: [
      new TerserPlugin({
        extractComments: false,
      }),
    ],
  },
  output: {
    filename: "[name].js",
    path: path.resolve(__dirname, "dist"),

    // Build a UMD bundle that can be used from a `<script>` tag, or imported
    // into a CommonJS / ESM environment.
    libraryTarget: "umd",
    library: "texLinebreak",

    // Make the UMD bundle usable in Node.
    // See https://github.com/webpack/webpack/issues/6522
    globalObject: "typeof self !== 'undefined' ? self : this",
  },
  /** Will serve demo page at http://localhost:3001/index.html */
  devServer: {
    port: 3001,
    static: {
      directory: "./src/demo/",
    },
    hot: false,
    liveReload: true,
    client: {
      overlay: {
        errors: true,
        warnings: false,
      },
    },
  },
  plugins: [
    new HtmlWebpackPlugin({
      inject: false,
      template: "./src/demo/demo.html",
    }),
    new LicensePlugin({
      outputFilename: "licenses.json",
      excludedPackageTest: (packageName, version) => {
        // This file is from the TeX Users Group, generated by Knuth.
        // It has no license, which should perhaps be investigated?
        return packageName.startsWith("hyphenation.en-us");
      },
    }),
    new BannerPlugin("For license information, see licenses.json"),

    new WebpackShellPluginNext({
      onBuildEnd: {
        scripts: [`npx dts-bundle-generator -o dist/index.d.ts src/exports.ts`],
        blocking: false,
        parallel: true,
      },
    }),
  ],
  stats: {
    assets: false,
    children: false,
    chunks: false,
    hash: false,
    modules: false,
    publicPath: false,
    timings: false,
    version: false,
    warnings: true,
  },
};
